syntax = "proto3";
package hooya;

message Tag {
    string namespace = 1;
    string descriptor = 2;
}

message File {
    bytes cid = 1;
    int64 size = 2;
    optional string mimetype = 3;
    ProcessingStatus processing_status = 4;
    oneof ext_file {
        Image image = 5;
        Video video = 6;
    }
    repeated Tag tags = 7;
}

message Image {
    int64 height = 1;
    int64 width = 2;
    float aspect_ratio = 3;
    repeated bytes colors = 4;
    repeated Thumbnail thumbnails = 5;
}

message Video {
    int64 height = 1;
    int64 width = 2;
    float aspect_ratio = 3;
    repeated Thumbnail thumbnails = 4;
    float duration = 5;
}

message Thumbnail {
    bytes cid = 1;
    int64 size = 2;
    string mimetype = 3;
    bytes source_cid = 4;
    int64 height = 5;
    int64 width = 6;
    float aspect_ratio = 7;
    bool is_animated = 8;
}

enum ProcessingStatus {
    PROCESSING_FINISHED = 0;
    PROCESSING_STARTED = 1;
    PROCESSING_FAILED = 2;
    THUMBNAIL_GENERATED = 3;
    VIDEO_PREVIEW_GENERATED = 4;
}

